codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      color:
        high: green
        medium: yellow
        low: red
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
