package com.aidcompass.auth.domain.authority;

public enum Authority {
    ACCOUNT_CREATE, ACCOUNT_DELETE, ACCOUNT_LOCK, ACCOUNT_UNABLE, SERVICE_ACCOUNT_MANAGER,
    TYPE_SUGGEST, TYPE_MANAGEMENT, TYPE_TRANSLATE_MANAGEMENT,
    SPECIALIST_CREATE_UPDATE, SPECIALIST_MANAGEMENT,
    REVIEW_CREATE_UPDATE, REVIEW_MANAGEMENT, REVIEWS_BUFFER_MANAGEMENT,
    OBSERVE
}
